export const Pathnames = {
  public: {
    home: "/",
    login: "/login",
    signIn: "/signin",
    events: "/events",
    forgotPassword: "/login/forgot-password",
    verifyAccount: "/verify-account",
    resetPassword: "/login/reset-password",
    confirmPasswordUpdate: "/change-my-password",
    confirmEmailUpdate: "/change-my-email",
  },
  participant: {
    home: "/",
    events: "/events",
    event: "/events/:id",
    profile: "/profile",
    myEvents: "/profile/events",
    logout: "/logout",
    confirmPasswordUpdate: "/change-my-password",
    confirmEmailUpdate: "/change-my-email",
  },
  manager: {
    home: "/",
    events: "/events",
    event: "/events/:id",
    profile: "/profile",
    myEvents: "/profile/events",
    locations: "/locations",
    location: "/location/:id",
    speakers: "/speakers",
    speaker: "/speakers/:id",
    logout: "/logout",
    confirmPasswordUpdate: "/change-my-password",
    confirmEmailUpdate: "/change-my-email",
  },
  admin: {
    home: "/",
    profile: "/profile",
    users: "/users",
    user: "/users/:id",
    logout: "/logout",
    confirmPasswordUpdate: "/change-my-password",
    confirmEmailUpdate: "/change-my-email",
  },
};
