GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.account TO ssbd01mok;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.role TO ssbd01mok;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.account_role TO ssbd01mok;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.personal_data TO ssbd01mok;