import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://team-1.proj-sum.it.p.lodz.pl/');
  await page.getByRole('menuitem', { name: 'Log in' }).getByRole('paragraph').click();
  await page.getByLabel('Username*').click();
  await page.getByLabel('Username*').fill('testAdmin');
  await page.getByLabel('Username*').press('Tab');
  await page.getByLabel('Password*').fill('P@ssw0rd');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByRole('menuitem', { name: 'Accounts' }).getByRole('paragraph').click();
  await page.getByRole('cell', { name: '0d3d8632-0ed6-4e43-8021-' }).click();
  await page.getByRole('tab', { name: 'Change profile details' }).click();
  await page.getByLabel('Name*', {exact: true}).click();
  await page.getByLabel('Name*', {exact: true}).fill('');
  await page.getByLabel('Name*', {exact: true}).fill('WandaPoZmianie');
  await page.getByRole('button', { name: 'save changes' }).first().click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('tab', { name: 'Profile details', exact: true }).click();
  await expect(page.getByRole('cell', { name: 'WandaPoZmianie' })).toBeVisible();
  await expect(page.getByText('Wanda', { exact: true })).toBeHidden();
  await page.getByRole('tab', { name: 'Change profile details' }).click();
  await page.getByLabel('Name*', {exact: true}).click();
  await page.getByLabel('Name*', {exact: true}).fill('');
  await page.getByLabel('Name*', {exact: true}).fill('Wanda');
  await page.getByRole('button', { name: 'save changes' }).first().click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('tab', { name: 'Profile details', exact: true }).click();
  await page.getByRole('cell', { name: 'Wanda', exact: true }).click();
});