import i18next from "i18next";
import { initReactI18next } from "react-i18next";
import { LanguageType } from "../types/enums/LanguageType.enum";

// const language = {
//   POLISH: {
//     profileDetailsHeading: "Szczegóły profilu",
//     tableKey: "Klucz",
//     tableValue: "Wartość",
//     tableUsername: "Nazwa użytkownika",
//     tableRoles: "Role",
//     tableFirstName: "Imię",
//     tableLastName: "Nazwisko",
//     tableGender: "Płeć",
//     tableIsActive: "Czy aktywny",
//     tableIsVerified: "Czy zweryfikowany",
//     tableIsUnlocked: "Czy odblokowany",
//     tableLanguagePreference: "Preferencje językowe",
//     eventsLink: "Wydarzenia",
//   },
//   ENGLISH: {
//     profileDetailsHeading: "Profile details",
//     tableKey: "Key",
//     tableValue: "Value",
//     tableUsername: "Username",
//     tableRoles: "Password",
//     tableFirstName: "First name",
//     tableLastName: "Last name",
//     tableGender: "Gender",
//     tableIsActive: "Is active",
//     tableIsVerified: "Is verified",
//     tableIsUnlocked: "Is unlocked",
//     tableLanguagePreference: "Language preference",
//     eventsLink: "Events",
//   },
// };

i18next.use(initReactI18next).init({
  resources: {
    POLISH: {
      translation: {
        accountsLink: "Konta",
        eventsLink: "Wydarzenia",
        logInLink: "Zaloguj się",
        registerLink: "Rejestracja",
        profileLink: "Profil",
        logOutLink: "Wyloguj",
        myEventsLink: "Moje wydarzenia",
        locationsLink: "Lokalizacje",
        speakersLink: "Prelegenci",

        roles: "Role",
        role: "Rola",
        userName: "Nazwa konta",
        firstName: "Imie",
        lastName: "Nazwisko",
        gender: "Płeć",
        isActive: "Aktywne",
        isVerified: "Zweryfikowe",
        isUnlocked: "Odblokowane",
        verify: "Strona z wydarzeniami",

        tableKey: "Klucz",
        tableValue: "Wartość",
        eventsHeading: "Wydarzenia",
        languagePref: "Preferencje językowe",
        lastSuccLogin: "Ostatnie poprawne logowanie",
        lastFailedLogin: "Ostatnie niepoprawne logowanie",
        lockedUntil: "Zablokowane do",
        notLocked: "Nie zablokowane",

        yes: "Tak",
        no: "Nie",
        never: "Nigdy",
        save: "zapisz",
        saveChanges: "zapisz zmiany",
        action: "Akcja",
        refreshData: "Odśwież Dane",
        home: "Strona główna",
        accounts: "Konta",
        accountDetails: "Szczegóły konta",
        gotoHomePage: "Wróć do strony głównej",
        confEmailChange: "Potwierdź swoją zmiane adresu email!",
        clickToConfEmail:
          "Naciśnij przycisk poniżej, aby potwierdzić zmiane email!",
        emailHasBeenChanged: "Adres email został zmieniony!",

        POLISH: "Polski",
        ENGLISH: "Angielski",

        ROLE_ADMIN: "Administrator",
        ROLE_PARTICIPANT: "Uczestnik",
        ROLE_MANAGER: "Zarządca",

        changePersonalData: "Zmień dane personalne",
        changePassword: "Zmień hasło",
        changeEmail: "Zmień adres e-mail",
        enterNewMail: "Wprowadź nowy adres e-mail poniżej",
        newEmail: "Nowy adres e-mail",
        newPassword: "Nowe hasło",
        confirmNewPassword: "Potwierdz nowe hasło",
        changeAccStatus: "Zmień status konta",
        activeDeactiveAcc: "Aktywuj lub dezaktywuj konto!",
        clickButBToChangePass:
          "Naciśnij poniższy przycisk, aby wysłać maila z linkiem do zmiany hasła!",
        enterNewPersonalData: "Podaj nowe dane personalne konta!",
        changeAccRole: "Zmień role konta",
        assignRemoveRoles: "Nadaj lub odbierz role!",
        addRole: "Nadaj rolę",
        chooseOneOfRoles: "Wybierz jedną z dostępnych ról do nadania!",
        rolesAssignedToAcc: "Role przypisane do konta",
        currentPassword: "Aktulane hasło",
        areYouSure: "Czy jesteś pewnien, że chcesz kontynuować?",
        confirmChange: "Potwierdź zmiane",
        profileDetails: "Dane konta",
        changeProfileDetails: "Zmień dane konta",
        manageAccounts: "Zarządzaj kontami",
        somethingHappened: "Stało się coś złego :((",
        errorConfPassword:
          "Wystąpił błąd podczas potwierdzania konta, jeżeli uważasz, że to pomyłka, skontaktuj się ze wsparciem",
        clickToConfPassChange:
          "Naciśnij przycisk na dole, aby potwierdzić zmiane hasła!",
        passwordHasBeenChanged: "Hasło zostało zmienione!",
        youCanGoToLogin: "Możesz przejść samemu na strone logowania, lub&#x20;",
        goBackToLoginPage: "Wróć do strony głównej",

        active: "Aktywne",
        inactive: "Nieaktywne",

        NotKnown: "Nieznana",
        Male: "Mężczyzna",
        Female: "Kobieta",
        NotSpecified: "Nie podano",
      },
    },
    ENGLISH: {
      translation: {
        accountsLink: "Accounts",
        eventsLink: "Events",
        logInLink: "Log In",
        registerLink: "Sign in",
        profileLink: "Profile",
        logOutLink: "Log-out",
        myEventsLink: "My events",
        locationsLink: "Locations",
        speakersLink: "Speakers",

        roles: "Roles",
        role: "Role",
        userName: "UserName",
        firstName: "First Name",
        lastName: "Last Name",
        gender: "Gender",
        isActive: "Is Active",
        isVerified: "Is Verified",
        isUnlocked: "Is Unlocked",
        verify: "Verify",
        eventPage: "Event Page",

        tableKey: "Key",
        tableValue: "Value",
        eventsHeading: "Events",
        languagePref: "Language preference",
        lastSuccLogin: "Last successful login",
        lastFailedLogin: "Last failed login",
        lockedUntil: "Locked until",
        notLocked: "Not Locked",

        yes: "Yes",
        no: "No",
        never: "Never",
        save: "save",
        saveChanges: "Save changes",
        action: "Action",
        refreshData: "Refresh Data",
        home: "Home",
        accounts: "Accounts",
        accountDetails: "Account details",
        gotoHomePage: "Go to home page",
        confEmailChange: "Confirm your email change!",
        confPassChange: "Confirm your password change!",
        clickToConfEmail:
          "Click the button below to confirm your email change!",
        emailHasBeenChanged: "Email has been changed!",

        POLISH: "Polish",
        ENGLISH: "English",

        ROLE_ADMIN: "Administrator",
        ROLE_PARTICIPANT: "Participant",
        ROLE_MANAGER: "Manager",

        changePersonalData: "Change personal data",
        changePassword: "Change password",
        changeEmail: "Change e-mail",
        enterNewMail: "Enter new e-mail address below!",
        newEmail: "New e-mail",
        newPassword: "New password",
        confirmNewPassword: "Confirm new password",
        changeAccStatus: "Change account's status",
        activeDeactiveAcc: "Activate or deactivate user's account!",
        clickButBToChangePass:
          "Click the button below to send an e-mail with password reset link!",
        enterNewPersonalData: "Enter account's new personal data below!",
        changeAccRole: "Change account's roles",
        assignRemoveRoles: "Assing or remove account's roles!",
        addRole: "Add role",
        chooseOneOfRoles: "Choose one of the available roles to add!",
        rolesAssignedToAcc: "Roles assigned to the account",
        currentPassword: "Current password",
        areYouSure: "Are you sure you want to procceed?",
        confirmChange: "Confirm change",
        profileDetails: "Profile details",
        changeProfileDetails: "Change personal data",
        manageAccounts: "Manage accounts",
        somethingHappened: "Something bad happened :((",
        errorConfPassword:
          "There was an error while confirming your email change. If you think this is a mistake, contact support.",
        clickToConfPassChange:
          "Click the button below to confirm your password change!",
        passwordHasBeenChanged: "Password has been changed!",
        youCanGoToLogin: "You can go to login page manually, or&#x20;",
        goBackToLoginPage: "Go back to login page",

        active: "Active",
        inactive: "Inactive",

        NotKnown: "Not Known",
        Male: "Male",
        Female: "Female",
        NotSpecified: "Not Specified",
      },
    },
  },
  lng:
    localStorage.getItem("language") ??
    (navigator.language === "pl" ? LanguageType.POLISH : LanguageType.ENGLISH),
});
export default i18next;
